import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1762530434786 implements MigrationInterface {
    name = 'InitialSchema1762530434786'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "firstName" varchar(120) NOT NULL, "lastName" varchar(120) NOT NULL, "email" varchar(120) NOT NULL, "password" varchar(255) NOT NULL, "phone" varchar(32), "role" text NOT NULL DEFAULT ('user'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "offers" ("id" varchar PRIMARY KEY NOT NULL, "loanApplicationId" varchar NOT NULL, "adminId" varchar, "lenderCode" varchar(64) NOT NULL DEFAULT ('BACKOFFICE'), "offeredLoanAmount" float NOT NULL, "apr" float NOT NULL, "termMonths" integer NOT NULL, "monthlyPayment" float NOT NULL, "totalInterest" float NOT NULL, "ltvAtOffer" float, "status" text NOT NULL DEFAULT ('ISSUED'), "expiresAt" datetime, "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "applicationId" varchar)`);
        await queryRunner.query(`CREATE INDEX "IDX_adf9d2f71913bbd7c6d7172d46" ON "offers" ("lenderCode") `);
        await queryRunner.query(`CREATE TABLE "loan_applications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar, "vehicleId" varchar NOT NULL, "applicantName" varchar(120) NOT NULL, "applicantEmail" varchar(120) NOT NULL, "applicantPhone" varchar(32), "bvn" varchar(20) NOT NULL, "nin" varchar(20), "dateOfBirth" date, "residentialAddress" text, "listingPrice" float NOT NULL, "snapshotRetailValue" float, "snapshotLoanValue" float, "valuationFetchedAt" datetime, "requestedLoanAmount" float, "requestedDownPaymentPct" float, "requestedDownPaymentAmount" float, "requestedTermMonths" integer NOT NULL, "requestedApr" float, "desiredLoanCurrency" text NOT NULL DEFAULT ('NGN'), "desiredMonthlyPayment" float, "desiredInterestRate" float, "desiredEquityContribution" float, "interestRateType" varchar(32), "desiredResidualBalloonPct" float, "desiredRepaymentDate" integer, "subscribeRoadworthiness" boolean NOT NULL DEFAULT (0), "subscribeLicenseRenewal" boolean NOT NULL DEFAULT (0), "feePaymentPreference" varchar(32), "upfrontPaymentItems" json, "ltvCap" float NOT NULL, "plannedDownAmount" float, "initialNeeded" float, "maxFinance" float, "validatedLoanAmount" float, "requiredExtraDown" float, "impliedMonthlyPayment" float, "impliedTotalInterest" float, "eligibilityStatus" text, "eligibilityReasons" text, "status" text NOT NULL DEFAULT ('SUBMITTED'), "isGuest" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_62cc84cd393f8b011693c0873c" ON "loan_applications" ("applicantEmail") `);
        await queryRunner.query(`CREATE TABLE "valuations" ("id" varchar PRIMARY KEY NOT NULL, "vehicleId" varchar NOT NULL, "retailValue" float NOT NULL, "loanValue" float NOT NULL, "source" text NOT NULL, "fetchedAt" datetime NOT NULL, "providerRef" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_e236b629bac439792309e7e14e" ON "valuations" ("fetchedAt") `);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" varchar PRIMARY KEY NOT NULL, "vin" varchar(32) NOT NULL, "make" varchar(64) NOT NULL, "model" varchar(64) NOT NULL, "trim" varchar(64), "year" integer NOT NULL, "mileage" integer, "vehicleType" text, "condition" text, "engine" varchar(128), "transmission" text, "driveType" text, "fuelType" varchar(64), "exteriorColor" varchar(64), "interiorColor" varchar(64), "address" text, "ownerId" varchar NOT NULL, "listingPrice" float, "currency" text NOT NULL DEFAULT ('NGN'), "requiredDownPaymentPct" float NOT NULL DEFAULT (0.4), "region" varchar(64), "retailValue" float, "loanValue" float, "valuationSource" text, "valuationFetchedAt" datetime, "status" text NOT NULL DEFAULT ('LISTED'), "isLoanAvailable" boolean NOT NULL DEFAULT (1), "minLoanValue" float, "maxLoanPeriodMonths" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8288ce015b69c5856cf54e07a6" ON "vehicles" ("vin") `);
        await queryRunner.query(`CREATE TABLE "vehicle_images" ("id" varchar PRIMARY KEY NOT NULL, "vehicleId" varchar NOT NULL, "url" text NOT NULL, "filename" text, "displayOrder" integer NOT NULL DEFAULT (0), "isPrimary" boolean NOT NULL DEFAULT (0), "caption" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a907b93045b8793801158fbba" ON "vehicle_images" ("vehicleId") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "type" text NOT NULL, "title" varchar NOT NULL, "message" text NOT NULL, "data" json, "read" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`DROP INDEX "IDX_adf9d2f71913bbd7c6d7172d46"`);
        await queryRunner.query(`CREATE TABLE "temporary_offers" ("id" varchar PRIMARY KEY NOT NULL, "loanApplicationId" varchar NOT NULL, "adminId" varchar, "lenderCode" varchar(64) NOT NULL DEFAULT ('BACKOFFICE'), "offeredLoanAmount" float NOT NULL, "apr" float NOT NULL, "termMonths" integer NOT NULL, "monthlyPayment" float NOT NULL, "totalInterest" float NOT NULL, "ltvAtOffer" float, "status" text NOT NULL DEFAULT ('ISSUED'), "expiresAt" datetime, "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "applicationId" varchar, CONSTRAINT "FK_6d911e68442dac48e56f96a93a3" FOREIGN KEY ("applicationId") REFERENCES "loan_applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_ebe79181adb8312caca9b13e4be" FOREIGN KEY ("adminId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_offers"("id", "loanApplicationId", "adminId", "lenderCode", "offeredLoanAmount", "apr", "termMonths", "monthlyPayment", "totalInterest", "ltvAtOffer", "status", "expiresAt", "notes", "createdAt", "updatedAt", "applicationId") SELECT "id", "loanApplicationId", "adminId", "lenderCode", "offeredLoanAmount", "apr", "termMonths", "monthlyPayment", "totalInterest", "ltvAtOffer", "status", "expiresAt", "notes", "createdAt", "updatedAt", "applicationId" FROM "offers"`);
        await queryRunner.query(`DROP TABLE "offers"`);
        await queryRunner.query(`ALTER TABLE "temporary_offers" RENAME TO "offers"`);
        await queryRunner.query(`CREATE INDEX "IDX_adf9d2f71913bbd7c6d7172d46" ON "offers" ("lenderCode") `);
        await queryRunner.query(`DROP INDEX "IDX_62cc84cd393f8b011693c0873c"`);
        await queryRunner.query(`CREATE TABLE "temporary_loan_applications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar, "vehicleId" varchar NOT NULL, "applicantName" varchar(120) NOT NULL, "applicantEmail" varchar(120) NOT NULL, "applicantPhone" varchar(32), "bvn" varchar(20) NOT NULL, "nin" varchar(20), "dateOfBirth" date, "residentialAddress" text, "listingPrice" float NOT NULL, "snapshotRetailValue" float, "snapshotLoanValue" float, "valuationFetchedAt" datetime, "requestedLoanAmount" float, "requestedDownPaymentPct" float, "requestedDownPaymentAmount" float, "requestedTermMonths" integer NOT NULL, "requestedApr" float, "desiredLoanCurrency" text NOT NULL DEFAULT ('NGN'), "desiredMonthlyPayment" float, "desiredInterestRate" float, "desiredEquityContribution" float, "interestRateType" varchar(32), "desiredResidualBalloonPct" float, "desiredRepaymentDate" integer, "subscribeRoadworthiness" boolean NOT NULL DEFAULT (0), "subscribeLicenseRenewal" boolean NOT NULL DEFAULT (0), "feePaymentPreference" varchar(32), "upfrontPaymentItems" json, "ltvCap" float NOT NULL, "plannedDownAmount" float, "initialNeeded" float, "maxFinance" float, "validatedLoanAmount" float, "requiredExtraDown" float, "impliedMonthlyPayment" float, "impliedTotalInterest" float, "eligibilityStatus" text, "eligibilityReasons" text, "status" text NOT NULL DEFAULT ('SUBMITTED'), "isGuest" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_2cb764a2462ec43648fcccd72de" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_73b0e79ff0bba3d42672902e5e1" FOREIGN KEY ("vehicleId") REFERENCES "vehicles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_loan_applications"("id", "userId", "vehicleId", "applicantName", "applicantEmail", "applicantPhone", "bvn", "nin", "dateOfBirth", "residentialAddress", "listingPrice", "snapshotRetailValue", "snapshotLoanValue", "valuationFetchedAt", "requestedLoanAmount", "requestedDownPaymentPct", "requestedDownPaymentAmount", "requestedTermMonths", "requestedApr", "desiredLoanCurrency", "desiredMonthlyPayment", "desiredInterestRate", "desiredEquityContribution", "interestRateType", "desiredResidualBalloonPct", "desiredRepaymentDate", "subscribeRoadworthiness", "subscribeLicenseRenewal", "feePaymentPreference", "upfrontPaymentItems", "ltvCap", "plannedDownAmount", "initialNeeded", "maxFinance", "validatedLoanAmount", "requiredExtraDown", "impliedMonthlyPayment", "impliedTotalInterest", "eligibilityStatus", "eligibilityReasons", "status", "isGuest", "createdAt", "updatedAt") SELECT "id", "userId", "vehicleId", "applicantName", "applicantEmail", "applicantPhone", "bvn", "nin", "dateOfBirth", "residentialAddress", "listingPrice", "snapshotRetailValue", "snapshotLoanValue", "valuationFetchedAt", "requestedLoanAmount", "requestedDownPaymentPct", "requestedDownPaymentAmount", "requestedTermMonths", "requestedApr", "desiredLoanCurrency", "desiredMonthlyPayment", "desiredInterestRate", "desiredEquityContribution", "interestRateType", "desiredResidualBalloonPct", "desiredRepaymentDate", "subscribeRoadworthiness", "subscribeLicenseRenewal", "feePaymentPreference", "upfrontPaymentItems", "ltvCap", "plannedDownAmount", "initialNeeded", "maxFinance", "validatedLoanAmount", "requiredExtraDown", "impliedMonthlyPayment", "impliedTotalInterest", "eligibilityStatus", "eligibilityReasons", "status", "isGuest", "createdAt", "updatedAt" FROM "loan_applications"`);
        await queryRunner.query(`DROP TABLE "loan_applications"`);
        await queryRunner.query(`ALTER TABLE "temporary_loan_applications" RENAME TO "loan_applications"`);
        await queryRunner.query(`CREATE INDEX "IDX_62cc84cd393f8b011693c0873c" ON "loan_applications" ("applicantEmail") `);
        await queryRunner.query(`DROP INDEX "IDX_e236b629bac439792309e7e14e"`);
        await queryRunner.query(`CREATE TABLE "temporary_valuations" ("id" varchar PRIMARY KEY NOT NULL, "vehicleId" varchar NOT NULL, "retailValue" float NOT NULL, "loanValue" float NOT NULL, "source" text NOT NULL, "fetchedAt" datetime NOT NULL, "providerRef" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_80cceca62367c2459f0eb75a929" FOREIGN KEY ("vehicleId") REFERENCES "vehicles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_valuations"("id", "vehicleId", "retailValue", "loanValue", "source", "fetchedAt", "providerRef", "createdAt") SELECT "id", "vehicleId", "retailValue", "loanValue", "source", "fetchedAt", "providerRef", "createdAt" FROM "valuations"`);
        await queryRunner.query(`DROP TABLE "valuations"`);
        await queryRunner.query(`ALTER TABLE "temporary_valuations" RENAME TO "valuations"`);
        await queryRunner.query(`CREATE INDEX "IDX_e236b629bac439792309e7e14e" ON "valuations" ("fetchedAt") `);
        await queryRunner.query(`DROP INDEX "IDX_8288ce015b69c5856cf54e07a6"`);
        await queryRunner.query(`CREATE TABLE "temporary_vehicles" ("id" varchar PRIMARY KEY NOT NULL, "vin" varchar(32) NOT NULL, "make" varchar(64) NOT NULL, "model" varchar(64) NOT NULL, "trim" varchar(64), "year" integer NOT NULL, "mileage" integer, "vehicleType" text, "condition" text, "engine" varchar(128), "transmission" text, "driveType" text, "fuelType" varchar(64), "exteriorColor" varchar(64), "interiorColor" varchar(64), "address" text, "ownerId" varchar NOT NULL, "listingPrice" float, "currency" text NOT NULL DEFAULT ('NGN'), "requiredDownPaymentPct" float NOT NULL DEFAULT (0.4), "region" varchar(64), "retailValue" float, "loanValue" float, "valuationSource" text, "valuationFetchedAt" datetime, "status" text NOT NULL DEFAULT ('LISTED'), "isLoanAvailable" boolean NOT NULL DEFAULT (1), "minLoanValue" float, "maxLoanPeriodMonths" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_c0a0d32b2ae04801d6e5b9e5c80" FOREIGN KEY ("ownerId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_vehicles"("id", "vin", "make", "model", "trim", "year", "mileage", "vehicleType", "condition", "engine", "transmission", "driveType", "fuelType", "exteriorColor", "interiorColor", "address", "ownerId", "listingPrice", "currency", "requiredDownPaymentPct", "region", "retailValue", "loanValue", "valuationSource", "valuationFetchedAt", "status", "isLoanAvailable", "minLoanValue", "maxLoanPeriodMonths", "createdAt", "updatedAt") SELECT "id", "vin", "make", "model", "trim", "year", "mileage", "vehicleType", "condition", "engine", "transmission", "driveType", "fuelType", "exteriorColor", "interiorColor", "address", "ownerId", "listingPrice", "currency", "requiredDownPaymentPct", "region", "retailValue", "loanValue", "valuationSource", "valuationFetchedAt", "status", "isLoanAvailable", "minLoanValue", "maxLoanPeriodMonths", "createdAt", "updatedAt" FROM "vehicles"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`ALTER TABLE "temporary_vehicles" RENAME TO "vehicles"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8288ce015b69c5856cf54e07a6" ON "vehicles" ("vin") `);
        await queryRunner.query(`DROP INDEX "IDX_9a907b93045b8793801158fbba"`);
        await queryRunner.query(`CREATE TABLE "temporary_vehicle_images" ("id" varchar PRIMARY KEY NOT NULL, "vehicleId" varchar NOT NULL, "url" text NOT NULL, "filename" text, "displayOrder" integer NOT NULL DEFAULT (0), "isPrimary" boolean NOT NULL DEFAULT (0), "caption" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_9a907b93045b8793801158fbba2" FOREIGN KEY ("vehicleId") REFERENCES "vehicles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_vehicle_images"("id", "vehicleId", "url", "filename", "displayOrder", "isPrimary", "caption", "createdAt") SELECT "id", "vehicleId", "url", "filename", "displayOrder", "isPrimary", "caption", "createdAt" FROM "vehicle_images"`);
        await queryRunner.query(`DROP TABLE "vehicle_images"`);
        await queryRunner.query(`ALTER TABLE "temporary_vehicle_images" RENAME TO "vehicle_images"`);
        await queryRunner.query(`CREATE INDEX "IDX_9a907b93045b8793801158fbba" ON "vehicle_images" ("vehicleId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_9a907b93045b8793801158fbba"`);
        await queryRunner.query(`ALTER TABLE "vehicle_images" RENAME TO "temporary_vehicle_images"`);
        await queryRunner.query(`CREATE TABLE "vehicle_images" ("id" varchar PRIMARY KEY NOT NULL, "vehicleId" varchar NOT NULL, "url" text NOT NULL, "filename" text, "displayOrder" integer NOT NULL DEFAULT (0), "isPrimary" boolean NOT NULL DEFAULT (0), "caption" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "vehicle_images"("id", "vehicleId", "url", "filename", "displayOrder", "isPrimary", "caption", "createdAt") SELECT "id", "vehicleId", "url", "filename", "displayOrder", "isPrimary", "caption", "createdAt" FROM "temporary_vehicle_images"`);
        await queryRunner.query(`DROP TABLE "temporary_vehicle_images"`);
        await queryRunner.query(`CREATE INDEX "IDX_9a907b93045b8793801158fbba" ON "vehicle_images" ("vehicleId") `);
        await queryRunner.query(`DROP INDEX "IDX_8288ce015b69c5856cf54e07a6"`);
        await queryRunner.query(`ALTER TABLE "vehicles" RENAME TO "temporary_vehicles"`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" varchar PRIMARY KEY NOT NULL, "vin" varchar(32) NOT NULL, "make" varchar(64) NOT NULL, "model" varchar(64) NOT NULL, "trim" varchar(64), "year" integer NOT NULL, "mileage" integer, "vehicleType" text, "condition" text, "engine" varchar(128), "transmission" text, "driveType" text, "fuelType" varchar(64), "exteriorColor" varchar(64), "interiorColor" varchar(64), "address" text, "ownerId" varchar NOT NULL, "listingPrice" float, "currency" text NOT NULL DEFAULT ('NGN'), "requiredDownPaymentPct" float NOT NULL DEFAULT (0.4), "region" varchar(64), "retailValue" float, "loanValue" float, "valuationSource" text, "valuationFetchedAt" datetime, "status" text NOT NULL DEFAULT ('LISTED'), "isLoanAvailable" boolean NOT NULL DEFAULT (1), "minLoanValue" float, "maxLoanPeriodMonths" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "vehicles"("id", "vin", "make", "model", "trim", "year", "mileage", "vehicleType", "condition", "engine", "transmission", "driveType", "fuelType", "exteriorColor", "interiorColor", "address", "ownerId", "listingPrice", "currency", "requiredDownPaymentPct", "region", "retailValue", "loanValue", "valuationSource", "valuationFetchedAt", "status", "isLoanAvailable", "minLoanValue", "maxLoanPeriodMonths", "createdAt", "updatedAt") SELECT "id", "vin", "make", "model", "trim", "year", "mileage", "vehicleType", "condition", "engine", "transmission", "driveType", "fuelType", "exteriorColor", "interiorColor", "address", "ownerId", "listingPrice", "currency", "requiredDownPaymentPct", "region", "retailValue", "loanValue", "valuationSource", "valuationFetchedAt", "status", "isLoanAvailable", "minLoanValue", "maxLoanPeriodMonths", "createdAt", "updatedAt" FROM "temporary_vehicles"`);
        await queryRunner.query(`DROP TABLE "temporary_vehicles"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8288ce015b69c5856cf54e07a6" ON "vehicles" ("vin") `);
        await queryRunner.query(`DROP INDEX "IDX_e236b629bac439792309e7e14e"`);
        await queryRunner.query(`ALTER TABLE "valuations" RENAME TO "temporary_valuations"`);
        await queryRunner.query(`CREATE TABLE "valuations" ("id" varchar PRIMARY KEY NOT NULL, "vehicleId" varchar NOT NULL, "retailValue" float NOT NULL, "loanValue" float NOT NULL, "source" text NOT NULL, "fetchedAt" datetime NOT NULL, "providerRef" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "valuations"("id", "vehicleId", "retailValue", "loanValue", "source", "fetchedAt", "providerRef", "createdAt") SELECT "id", "vehicleId", "retailValue", "loanValue", "source", "fetchedAt", "providerRef", "createdAt" FROM "temporary_valuations"`);
        await queryRunner.query(`DROP TABLE "temporary_valuations"`);
        await queryRunner.query(`CREATE INDEX "IDX_e236b629bac439792309e7e14e" ON "valuations" ("fetchedAt") `);
        await queryRunner.query(`DROP INDEX "IDX_62cc84cd393f8b011693c0873c"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" RENAME TO "temporary_loan_applications"`);
        await queryRunner.query(`CREATE TABLE "loan_applications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar, "vehicleId" varchar NOT NULL, "applicantName" varchar(120) NOT NULL, "applicantEmail" varchar(120) NOT NULL, "applicantPhone" varchar(32), "bvn" varchar(20) NOT NULL, "nin" varchar(20), "dateOfBirth" date, "residentialAddress" text, "listingPrice" float NOT NULL, "snapshotRetailValue" float, "snapshotLoanValue" float, "valuationFetchedAt" datetime, "requestedLoanAmount" float, "requestedDownPaymentPct" float, "requestedDownPaymentAmount" float, "requestedTermMonths" integer NOT NULL, "requestedApr" float, "desiredLoanCurrency" text NOT NULL DEFAULT ('NGN'), "desiredMonthlyPayment" float, "desiredInterestRate" float, "desiredEquityContribution" float, "interestRateType" varchar(32), "desiredResidualBalloonPct" float, "desiredRepaymentDate" integer, "subscribeRoadworthiness" boolean NOT NULL DEFAULT (0), "subscribeLicenseRenewal" boolean NOT NULL DEFAULT (0), "feePaymentPreference" varchar(32), "upfrontPaymentItems" json, "ltvCap" float NOT NULL, "plannedDownAmount" float, "initialNeeded" float, "maxFinance" float, "validatedLoanAmount" float, "requiredExtraDown" float, "impliedMonthlyPayment" float, "impliedTotalInterest" float, "eligibilityStatus" text, "eligibilityReasons" text, "status" text NOT NULL DEFAULT ('SUBMITTED'), "isGuest" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "loan_applications"("id", "userId", "vehicleId", "applicantName", "applicantEmail", "applicantPhone", "bvn", "nin", "dateOfBirth", "residentialAddress", "listingPrice", "snapshotRetailValue", "snapshotLoanValue", "valuationFetchedAt", "requestedLoanAmount", "requestedDownPaymentPct", "requestedDownPaymentAmount", "requestedTermMonths", "requestedApr", "desiredLoanCurrency", "desiredMonthlyPayment", "desiredInterestRate", "desiredEquityContribution", "interestRateType", "desiredResidualBalloonPct", "desiredRepaymentDate", "subscribeRoadworthiness", "subscribeLicenseRenewal", "feePaymentPreference", "upfrontPaymentItems", "ltvCap", "plannedDownAmount", "initialNeeded", "maxFinance", "validatedLoanAmount", "requiredExtraDown", "impliedMonthlyPayment", "impliedTotalInterest", "eligibilityStatus", "eligibilityReasons", "status", "isGuest", "createdAt", "updatedAt") SELECT "id", "userId", "vehicleId", "applicantName", "applicantEmail", "applicantPhone", "bvn", "nin", "dateOfBirth", "residentialAddress", "listingPrice", "snapshotRetailValue", "snapshotLoanValue", "valuationFetchedAt", "requestedLoanAmount", "requestedDownPaymentPct", "requestedDownPaymentAmount", "requestedTermMonths", "requestedApr", "desiredLoanCurrency", "desiredMonthlyPayment", "desiredInterestRate", "desiredEquityContribution", "interestRateType", "desiredResidualBalloonPct", "desiredRepaymentDate", "subscribeRoadworthiness", "subscribeLicenseRenewal", "feePaymentPreference", "upfrontPaymentItems", "ltvCap", "plannedDownAmount", "initialNeeded", "maxFinance", "validatedLoanAmount", "requiredExtraDown", "impliedMonthlyPayment", "impliedTotalInterest", "eligibilityStatus", "eligibilityReasons", "status", "isGuest", "createdAt", "updatedAt" FROM "temporary_loan_applications"`);
        await queryRunner.query(`DROP TABLE "temporary_loan_applications"`);
        await queryRunner.query(`CREATE INDEX "IDX_62cc84cd393f8b011693c0873c" ON "loan_applications" ("applicantEmail") `);
        await queryRunner.query(`DROP INDEX "IDX_adf9d2f71913bbd7c6d7172d46"`);
        await queryRunner.query(`ALTER TABLE "offers" RENAME TO "temporary_offers"`);
        await queryRunner.query(`CREATE TABLE "offers" ("id" varchar PRIMARY KEY NOT NULL, "loanApplicationId" varchar NOT NULL, "adminId" varchar, "lenderCode" varchar(64) NOT NULL DEFAULT ('BACKOFFICE'), "offeredLoanAmount" float NOT NULL, "apr" float NOT NULL, "termMonths" integer NOT NULL, "monthlyPayment" float NOT NULL, "totalInterest" float NOT NULL, "ltvAtOffer" float, "status" text NOT NULL DEFAULT ('ISSUED'), "expiresAt" datetime, "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "applicationId" varchar)`);
        await queryRunner.query(`INSERT INTO "offers"("id", "loanApplicationId", "adminId", "lenderCode", "offeredLoanAmount", "apr", "termMonths", "monthlyPayment", "totalInterest", "ltvAtOffer", "status", "expiresAt", "notes", "createdAt", "updatedAt", "applicationId") SELECT "id", "loanApplicationId", "adminId", "lenderCode", "offeredLoanAmount", "apr", "termMonths", "monthlyPayment", "totalInterest", "ltvAtOffer", "status", "expiresAt", "notes", "createdAt", "updatedAt", "applicationId" FROM "temporary_offers"`);
        await queryRunner.query(`DROP TABLE "temporary_offers"`);
        await queryRunner.query(`CREATE INDEX "IDX_adf9d2f71913bbd7c6d7172d46" ON "offers" ("lenderCode") `);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "IDX_9a907b93045b8793801158fbba"`);
        await queryRunner.query(`DROP TABLE "vehicle_images"`);
        await queryRunner.query(`DROP INDEX "IDX_8288ce015b69c5856cf54e07a6"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP INDEX "IDX_e236b629bac439792309e7e14e"`);
        await queryRunner.query(`DROP TABLE "valuations"`);
        await queryRunner.query(`DROP INDEX "IDX_62cc84cd393f8b011693c0873c"`);
        await queryRunner.query(`DROP TABLE "loan_applications"`);
        await queryRunner.query(`DROP INDEX "IDX_adf9d2f71913bbd7c6d7172d46"`);
        await queryRunner.query(`DROP TABLE "offers"`);
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
